name: 🧠 Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Fetch LeetCode Stats and Update README
      uses: DenverCoder1/github-readme-stats@main
      with:
        username: hansraj61
        plugin_leetcode: yes
